Adjust move speed based on framerate & info log framerate

diff --git a/run b/run
--- a/run
+++ b/run
@@ -3,4 +3,10 @@
 # turn on env_log logging
 export RUST_LOG=wgpu_grapher=info
 
-target/debug/wgpu_grapher
+if [[ "$1" != "debug" && "$1" != "release" ]]; then
+  echo "Required arg: debug or release."
+  exit 2
+fi
+
+target/$1/wgpu_grapher
+
